apiVersion: v1
kind: Secret
metadata:
  name:  backend-secret
  Namespace: mean-crud
type: Opaque
stringData: 
    MONGO_URI: "mongodb+srv://saikat:saikat1998@cluster0.dhcvisx.mongodb.net/?appName=Cluster0"