name: Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 763103708432

  ECR_BACKEND: mean-crud-backend
  ECR_FRONTEND: mean-crud-frontend

  EKS_CLUSTER: mean-crud-eks

  NAMESPACE: mean-crud

jobs:

  deploy:

    name: Build and Deploy

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: us-east-1
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Confirm ECR login
        run: echo "Logged in to ECR"
      - name: Generate image tag
        id: image
        run: |
          echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "Generated image tag: ${{ steps.image.outputs.tag }} ${GITHUB_SHA::7}"
      - name: Build backend
        run: |
          docker build \
            -t ${{ env.ECR_BACKEND }}:${{ steps.image.outputs.tag }} \
            ./backend
      - name: Build Frontend
        run: |
          docker build \
            -t ${{ env.ECR_FRONTEND }}:${{ steps.image.outputs.tag }} \
            ./frontend
      - name: Tag backend
        run: |
          docker tag \
            ${{ env.ECR_BACKEND }}:${{ steps.image.outputs.tag }} \
            ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_BACKEND }}:${{ steps.image.outputs.tag }}

      - name: Tag frontend
        run: |
          docker tag \
            ${{ env.ECR_FRONTEND }}:${{ steps.image.outputs.tag }} \
            ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_FRONTEND }}:${{ steps.image.outputs.tag }}
      - name: Push backend
        run: |
          docker push \
            ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_BACKEND }}:${{ steps.image.outputs.tag }}
      - name: Push frontend
        run: |
          docker push \
            ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_FRONTEND }}:${{ steps.image.outputs.tag }}
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f K8s/backend-deployment.yaml -n $NAMESPACE
          kubectl apply -f K8s/frontend-deployment.yaml -n $NAMESPACE
          kubectl apply -f K8s/backend-service.yaml -n $NAMESPACE
          kubectl apply -f K8s/frontend-service.yaml -n $NAMESPACE
          kubectl apply -f K8s/ingress-class.yaml -n $NAMESPACE
          kubectl delete ingress mean-crud-ingress \
          -n $NAMESPACE \
          --ignore-not-found
          kubectl apply -f K8s/ingress.yaml -n $NAMESPACE

      - name: Debug EKS Auto Mode Load Balancer
        run: |
          echo "===== EKS AUTO MODE ====="

          aws eks describe-cluster \
            --name $EKS_CLUSTER \
            --region $AWS_REGION \
            --query 'cluster.computeConfig' \
            --output yaml

          echo "===== INGRESS CLASSES ====="

          kubectl get ingressclass -o yaml

          echo "===== ALB INGRESS CLASS ====="

          kubectl describe ingressclass alb

          echo "===== INGRESS ====="

          kubectl get ingress mean-crud-ingress \
            -n $NAMESPACE \
            -o yaml

          echo "===== INGRESS EVENTS ====="

          kubectl describe ingress mean-crud-ingress \
            -n $NAMESPACE

          echo "===== SERVICES ====="

          kubectl get svc \
            -n $NAMESPACE \
            -o wide

          echo "===== ENDPOINTS ====="

          kubectl get endpoints \
            -n $NAMESPACE \
            -o wide

          echo "===== AWS LOAD BALANCERS ====="

          aws elbv2 describe-load-balancers \
            --region $AWS_REGION \
            --query 'LoadBalancers[*].[LoadBalancerName,DNSName,State.Code,Scheme,Type]' \
            --output table
      - name: Update backend
        run: |
          kubectl -n $NAMESPACE set image \
            deployment/backend-deployment \
            backend=${{ secrets.ECR_REGISTRY }}/${{ env.ECR_BACKEND }}:${{ steps.image.outputs.tag }}
      - name: Update frontend
        run: |
          kubectl -n $NAMESPACE set image \
            deployment/frontend-deployment \
            frontend=${{ secrets.ECR_REGISTRY }}/${{ env.ECR_FRONTEND }}:${{ steps.image.outputs.tag }}
      - name: Wait for backend
        run: |
          kubectl -n $NAMESPACE rollout status \
            deployment/backend-deployment \
            --timeout=5m
      - name: Wait for frontend
        run: |
          kubectl -n $NAMESPACE rollout status \
            deployment/frontend-deployment \
            --timeout=5m
      - name: Verify ingress
        run: |
          kubectl get ingress -n $NAMESPACE -o wide
      - name: Debug Ingress and ALB
        run: |
          echo "===== Kubernetes Nodes ====="
          kubectl get nodes

          echo "===== All Resources ====="
          kubectl get all -n $NAMESPACE

          echo "===== Ingress ====="
          kubectl get ingress -n $NAMESPACE -o wide

          echo "===== Ingress Description ====="
          kubectl describe ingress mean-crud-ingress -n $NAMESPACE

          echo "===== AWS Load Balancer Controller ====="
          kubectl get deployment -n kube-system aws-load-balancer-controller

          echo "===== AWS Load Balancer Controller Pods ====="
          kubectl get pods -n kube-system | grep aws-load-balancer-controller

          echo "===== AWS Load Balancer Controller Logs ====="
          kubectl logs \
            -n kube-system \
            deployment/aws-load-balancer-controller \
            --tail=200
